version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf

  php:
    build: php-fpm
    volumes:
      - ./:/code

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8183:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
